// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OJBlazor.Share.DataModels;

#nullable disable

namespace OJBlazor.Share.Migrations
{
    [DbContext(typeof(OJContext))]
    partial class OJContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("OJBlazor.Share.DataModels.CourseModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserModelId")
                        .HasColumnType("varchar(256)");

                    b.HasKey("Name");

                    b.HasIndex("UserModelId");

                    b.ToTable("CourseModels");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.TestModel", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Arg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CourseModelName")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Intro")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.HasIndex("CourseModelName");

                    b.ToTable("TestModels");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.UserModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UserModels");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.CourseModel", b =>
                {
                    b.HasOne("OJBlazor.Share.DataModels.UserModel", null)
                        .WithMany("LearnCourses")
                        .HasForeignKey("UserModelId");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.TestModel", b =>
                {
                    b.HasOne("OJBlazor.Share.DataModels.CourseModel", null)
                        .WithMany("Tests")
                        .HasForeignKey("CourseModelName");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.CourseModel", b =>
                {
                    b.Navigation("Tests");
                });

            modelBuilder.Entity("OJBlazor.Share.DataModels.UserModel", b =>
                {
                    b.Navigation("LearnCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
